import Footer from "@/components/Footer"
import { Navbar } from "@/components/Navbar"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="flex flex-col min-h-[calc(100vh-3.5rem-1px)]">
          <main className="flex flex-col flex-1 h-full">{children}</main>
          <Footer />
        </div>
        <Toaster />
      </body>
    </html>
  )
}
